# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "games", :force => true do |t|
    t.column "away_id",    :integer
    t.column "away_team",  :string
    t.column "away_score", :integer
    t.column "home_id",    :integer
    t.column "home_team",  :string
    t.column "home_score", :integer
    t.column "played_on",  :date
    t.column "updated_on", :date
  end

  create_table "users", :force => true do |t|
    t.column "name", :string
  end

end
